name: Self-hosted Renovate
description: Run renovate

inputs:
  dry-run:
    description: "Run Renovate in dry-run mode"
    required: false
    default: "false"
  renovate-version:
    description: >-
      Renovate version to use (image tag).
      Leave empty to use the version specified in this repo, which is updated in sync with that of the renovate action.
      Alternatively, specify it and include the `renovate-version.json5` preset to have it updated.
    required: false
    # Renovate updates the line below. Please keep its formatting as it is.
    default: 39.171.2@sha256:b0f523458df1b52f9dc7ac0aa36a0eed759f9efc11e8530feaf0cf126b9e7cc7 # renovate-version
runs:
  using: composite
  steps:
    - name: retrieve secrets
      id: get-secrets
      uses: grafana/shared-workflows/actions/get-vault-secrets@f4fff1b7e6f54f37da5dbc3f957a60b865896a57
      with:
        common_secrets: |
          GRAFANA_RENOVATE_APP_ID=grafana-renovate-app:app-id
          GRAFANA_RENOVATE_PRIVATE_KEY=grafana-renovate-app:private-key

    - name: create GitHub app token
      id: app-token
      uses: actions/create-github-app-token@0d564482f06ca65fa9e77e2510873638c82206f2 # v1
      with:
        app-id: ${{ env.GRAFANA_RENOVATE_APP_ID }}
        private-key: ${{ env.GRAFANA_RENOVATE_PRIVATE_KEY }}
        owner: ${{ github.repository_owner }}

    - name: Self-hosted Renovate
      uses: renovatebot/github-action@e084b5ac6fd201023db6dd7743aec023babb02c8 # v41.0.13
      with:
        renovate-version: ${{ inputs.renovate-version }}
        token: ${{ steps.app-token.outputs.token }}
      env:
        LOG_LEVEL: debug
        RENOVATE_DRY_RUN: ${{ inputs.dry-run }}
        RENOVATE_PLATFORM: github
        RENOVATE_REPOSITORIES: ${{ github.repository }}
        RENOVATE_USERNAME: GrafanaRenovateBot
