name: Self-hosted Renovate
description: Run renovate

inputs:
  dry-run:
    description: "Run Renovate in dry-run mode"
    required: false
    default: "false"
  renovate-version:
    description: >-
      Renovate version to use (image tag).
      Leave empty to use the version specified in this repo, which is updated in sync with that of the renovate action.
      Alternatively, specify it and include the `renovate-version.json5` preset to have it updated.
    required: false
    # Renovate updates the line below. Please keep its formatting as it is.
    default: 39.179.0@sha256:57fc71b5e1b2d6987f61e7bcfc381eabdfdb0ba6aba4d55a53947e44c58e86b0 # renovate-version
runs:
  using: composite
  steps:
    - name: retrieve secrets
      id: get-secrets
      uses: grafana/shared-workflows/actions/get-vault-secrets@a7bc5367c4a91c389526d58839d8f6224dba4dcc
      with:
        common_secrets: |
          GRAFANA_RENOVATE_APP_ID=grafana-renovate-app:app-id
          GRAFANA_RENOVATE_PRIVATE_KEY=grafana-renovate-app:private-key

    - name: create GitHub app token
      id: app-token
      uses: actions/create-github-app-token@21cfef2b496dd8ef5b904c159339626a10ad380e # v1
      with:
        app-id: ${{ env.GRAFANA_RENOVATE_APP_ID }}
        private-key: ${{ env.GRAFANA_RENOVATE_PRIVATE_KEY }}
        owner: ${{ github.repository_owner }}

    - name: Self-hosted Renovate
      uses: renovatebot/github-action@02f4fdeb479bbb229caa7ad82cb5e691c07e80b3 # v41.0.14
      with:
        renovate-version: ${{ inputs.renovate-version }}
        token: ${{ steps.app-token.outputs.token }}
      env:
        LOG_LEVEL: debug
        RENOVATE_DRY_RUN: ${{ inputs.dry-run }}
        RENOVATE_PLATFORM: github
        RENOVATE_REPOSITORIES: ${{ github.repository }}
        RENOVATE_USERNAME: GrafanaRenovateBot
