name: Self-hosted Renovate
description: Run renovate

inputs:
  dry-run:
    description: "Run Renovate in dry-run mode"
    required: false
    default: "false"
  renovate-version:
    description: >-
      Renovate version to use (image tag).
      Leave empty to use the latest version, updated in sync with renovate-validate.
    required: false
    # Renovate updates the line below. Please keep its formatting as it is.
    default: 39.21.1@sha256:74552474bf5045650d162cfc64a8e270112c2ab21245a5ae5c2624a80c6200cf # renovate-version
runs:
  using: composite
  steps:
    - name: retrieve secrets
      id: get-secrets
      uses: grafana/shared-workflows/actions/get-vault-secrets@1bdb3a48906e610f13acdf4a1990dca485c85497
      with:
        common_secrets: |
          GRAFANA_RENOVATE_APP_ID=grafana-renovate-app:app-id
          GRAFANA_RENOVATE_PRIVATE_KEY=grafana-renovate-app:private-key

    - name: create GitHub app token
      id: app-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ env.GRAFANA_RENOVATE_APP_ID }}
        private-key: ${{ env.GRAFANA_RENOVATE_PRIVATE_KEY }}
        owner: ${{ github.repository_owner }}

    - name: Self-hosted Renovate
      uses: renovatebot/github-action@dd4d265eb8646cd04fc5f86ff8bc8d496d75a251 # v40.2.8
      with:
        renovate-version: ${{ inputs.renovate-version }}
        token: ${{ steps.app-token.outputs.token }}
      env:
        LOG_LEVEL: debug
        RENOVATE_DRY_RUN: ${{ inputs.dry-run }}
        RENOVATE_PLATFORM: github
        RENOVATE_REPOSITORIES: ${{ github.repository }}
        RENOVATE_USERNAME: GrafanaRenovateBot
