#!/bin/sh
#
# This scripts exists to pass `--enabled` to renovate on the command line.
#
# This is necessary because renovate app and MendRenovate are stubborn
# (surprise!) and they keep trying to run if they get access to the repository
# and they find a configuration file. In order to disable that, the
# configuration file needs to _disable_ renovate, and the only way to enable it
# back, beyond where renovate app and MendRenovate are able to see it, is to pass
# the `--enabled` flag on the command line.
#
# The renovate github action takes a `docker-cmd-file` parameter that specifies
# a *file* to copy into the container where renovate is going to run, and it's
# used as the command to run in the container.
#
# This is that file.
#
# Rube Goldberg would be proud.

set -x

renovate --enabled --force-cli
