# This is _NOT_ a reusable workflow, but rather the renovate run for this repo itself.
name: Self-hosted Renovate

on:
  schedule:
    - cron: "22 */4 * * *"
  workflow_dispatch:

jobs:
  renovate:
    uses: grafana/sm-renovate/.github/workflows/renovate.yaml
